### ISSUE TITLE
TODO - v1.1

### ISSUE THREAD

**Issue by Loxoz** [Loxoz/Barely-vanilla#1]
- [x] ➖ **REMOVE** fast furnace/workbench mods
- [x] 🏷️ **RESTORE** vanilla food levels tweaked by pam's harvestcraft
- [x] ➕ **ADD** botania
- [x] ➕ **ADD** chest transporter
- [x] ➕ **ADD** crafting tweaks
