### ISSUE TITLE
TODO - v1.2

### ISSUE THREAD

**Issue by Loxoz** [Loxoz/Barely-vanilla#2]
- [x] ➕ **ADD** disease to trees (try the feature)
- [x] ✔️ **FIX** season not continuing when no players are online
- [x] ➖ **REMOVE** Materialis mod (useless for this pack)
- [x] ➖ **REMOVE** elevator mod (since it doesn't goes with the mood of this modpack)
- [x] ➕ **ADD** CraftTweaker
  - [x] 🏷️ **CHANGE** mystical watering cans to require preceding tiers
  - [x] 🏷️ **CHANGE** How to get magma shards:
    - 1x magma shard from 1x magma block in the crafting table
    - 1x magma block from 1x magma shard in the furnace
  - [x] 🏷️ **CHANGE** The block breaker craft from random things to use an iron rod from quark
  - [x] 🏷️ **CHANGE** The cfm recipes to be easier
  - see in the `scripts/` folder for more infos
- [x] ➖ **REMOVE** Chicken chunks
- [x] ➕ **ADD** FTB Utilities for chunks instead (without the commands like home, warp, spawn...)
- [x] ➖ **DISABLE** Wub Wub from Tiny progression
- [x] 🏷️ **CHANGE** Stack size for the purified water bottle (to 3)
- [x] ➕ **ADD** Ability to sneak rightclick the sky while it's raining to refill your thirst
- [x] 🏷️ **TWEAK** Tiny Progression & Random things to accord with the modpack
- [x] ➕ **ADD** Bottled Milk (and tweak stack size to 2)
- [x] ➕ **ADD** Mouse Tweaks (and only enable shift click sliding)
- [x] ➕ **ADD** Starting items when the player spawns (3 purified water bottles, 8 apples, all books (botania lexicon))
