### ISSUE TITLE
TODO - v1.3

### ISSUE THREAD

**Issue by Loxoz** [Loxoz/Barely-vanilla#3]
- 🏷️ **CraftTweaker**:
  - [ ] ➕ **ADD** Being able to create purified water using water essence
  - [x] ✔️ **FIX** The amount of ceiling lamps from cfm back to 4 because of a fail to the new custom craft
- [x] ➕ **ADD** Thermal mods
